version: 2.1
jobs:
  test:
    parameters:
      docker_image:
        type: string
    docker:
      - image: << parameters.docker_image >>:latest
    working_directory: ~/.gap/pkg/CAP_project
    steps:
      - checkout
      - run: |
          cd ..
          git clone --depth 1 https://github.com/gap-packages/AutoDoc.git
          git clone --depth 1 https://github.com/homalg-project/homalg_project.git
          cd CAP_project
          make -C CAP doc
          make -C CompilerForCAP doc
          make -C MonoidalCategories doc
          make -C CartesianCategories doc
          make -C FreydCategoriesForCAP doc
          make --trace -j 4 --output-sync ci-test
workflows:
  version: 2
  commit:
    jobs:
      - test:
          docker_image: ghcr.io/homalg-project/gap-docker
          filters:
            branches:
              only:
                - master
                - /.*-ci/
  nightly:
    triggers:
      - schedule:
          # 0:00 UTC = 1:00 CET = 2:00 CEST
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test:
          docker_image: ghcr.io/homalg-project/gap-docker-master
